// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/crypto/v1/crypto.proto

package cryptov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ChainId       int32                  `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	WalletType    string                 `protobuf:"bytes,4,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateWalletRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateWalletRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreateWalletRequest) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletProto           `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetWallet() *WalletProto {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletProto           `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletResponse) GetWallet() *WalletProto {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ProcessDepositRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DepositId        string                 `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TxHash           string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId          int32                  `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,6,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessDepositRequest) Reset() {
	*x = ProcessDepositRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDepositRequest) ProtoMessage() {}

func (x *ProcessDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDepositRequest.ProtoReflect.Descriptor instead.
func (*ProcessDepositRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessDepositRequest) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

func (x *ProcessDepositRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ProcessDepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProcessDepositRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ProcessDepositRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ProcessDepositRequest) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

type ProcessDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposit       *DepositProto          `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDepositResponse) Reset() {
	*x = ProcessDepositResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDepositResponse) ProtoMessage() {}

func (x *ProcessDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDepositResponse.ProtoReflect.Descriptor instead.
func (*ProcessDepositResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessDepositResponse) GetDeposit() *DepositProto {
	if x != nil {
		return x.Deposit
	}
	return nil
}

type RequestWithdrawalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId     string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ToAddress        string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	ChainId          int32                  `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,6,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestWithdrawalRequest) Reset() {
	*x = RequestWithdrawalRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawalRequest) ProtoMessage() {}

func (x *RequestWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*RequestWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{6}
}

func (x *RequestWithdrawalRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *RequestWithdrawalRequest) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

type RequestWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *WithdrawalProto       `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithdrawalResponse) Reset() {
	*x = RequestWithdrawalResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawalResponse) ProtoMessage() {}

func (x *RequestWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*RequestWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *RequestWithdrawalResponse) GetWithdrawal() *WithdrawalProto {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type ProcessWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWithdrawalRequest) Reset() {
	*x = ProcessWithdrawalRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWithdrawalRequest) ProtoMessage() {}

func (x *ProcessWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*ProcessWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessWithdrawalRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

type ProcessWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *WithdrawalProto       `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWithdrawalResponse) Reset() {
	*x = ProcessWithdrawalResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWithdrawalResponse) ProtoMessage() {}

func (x *ProcessWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*ProcessWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessWithdrawalResponse) GetWithdrawal() *WithdrawalProto {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type InternalTransferRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromWalletId     string                 `protobuf:"bytes,2,opt,name=from_wallet_id,json=fromWalletId,proto3" json:"from_wallet_id,omitempty"`
	ToWalletId       string                 `protobuf:"bytes,3,opt,name=to_wallet_id,json=toWalletId,proto3" json:"to_wallet_id,omitempty"`
	FromAccountId    string                 `protobuf:"bytes,4,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId      string                 `protobuf:"bytes,5,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,6,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InternalTransferRequest) Reset() {
	*x = InternalTransferRequest{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTransferRequest) ProtoMessage() {}

func (x *InternalTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTransferRequest.ProtoReflect.Descriptor instead.
func (*InternalTransferRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{10}
}

func (x *InternalTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *InternalTransferRequest) GetFromWalletId() string {
	if x != nil {
		return x.FromWalletId
	}
	return ""
}

func (x *InternalTransferRequest) GetToWalletId() string {
	if x != nil {
		return x.ToWalletId
	}
	return ""
}

func (x *InternalTransferRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *InternalTransferRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *InternalTransferRequest) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

type InternalTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *TransferProto         `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalTransferResponse) Reset() {
	*x = InternalTransferResponse{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTransferResponse) ProtoMessage() {}

func (x *InternalTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTransferResponse.ProtoReflect.Descriptor instead.
func (*InternalTransferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{11}
}

func (x *InternalTransferResponse) GetTransfer() *TransferProto {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type WalletProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ChainId       int32                  `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	WalletType    string                 `protobuf:"bytes,5,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletProto) Reset() {
	*x = WalletProto{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletProto) ProtoMessage() {}

func (x *WalletProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletProto.ProtoReflect.Descriptor instead.
func (*WalletProto) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{12}
}

func (x *WalletProto) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletProto) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WalletProto) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WalletProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletProto) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *WalletProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DepositProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DepositId        string                 `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TxHash           string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId          int32                  `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,6,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Confirmations    int32                  `protobuf:"varint,8,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DepositProto) Reset() {
	*x = DepositProto{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositProto) ProtoMessage() {}

func (x *DepositProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositProto.ProtoReflect.Descriptor instead.
func (*DepositProto) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{13}
}

func (x *DepositProto) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

func (x *DepositProto) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DepositProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DepositProto) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DepositProto) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *DepositProto) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *DepositProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DepositProto) GetConfirmations() int32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

type WithdrawalProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId     string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ToAddress        string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	ChainId          int32                  `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,6,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	FeeMinorUnits    int64                  `protobuf:"varint,7,opt,name=fee_minor_units,json=feeMinorUnits,proto3" json:"fee_minor_units,omitempty"`
	TxHash           string                 `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WithdrawalProto) Reset() {
	*x = WithdrawalProto{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalProto) ProtoMessage() {}

func (x *WithdrawalProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalProto.ProtoReflect.Descriptor instead.
func (*WithdrawalProto) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{14}
}

func (x *WithdrawalProto) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *WithdrawalProto) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WithdrawalProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WithdrawalProto) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *WithdrawalProto) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WithdrawalProto) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *WithdrawalProto) GetFeeMinorUnits() int64 {
	if x != nil {
		return x.FeeMinorUnits
	}
	return 0
}

func (x *WithdrawalProto) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *WithdrawalProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransferProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromWalletId     string                 `protobuf:"bytes,2,opt,name=from_wallet_id,json=fromWalletId,proto3" json:"from_wallet_id,omitempty"`
	ToWalletId       string                 `protobuf:"bytes,3,opt,name=to_wallet_id,json=toWalletId,proto3" json:"to_wallet_id,omitempty"`
	FromAccountId    string                 `protobuf:"bytes,4,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId      string                 `protobuf:"bytes,5,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	ChainId          int32                  `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AmountMinorUnits int64                  `protobuf:"varint,7,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferProto) Reset() {
	*x = TransferProto{}
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProto) ProtoMessage() {}

func (x *TransferProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_v1_crypto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProto.ProtoReflect.Descriptor instead.
func (*TransferProto) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_v1_crypto_proto_rawDescGZIP(), []int{15}
}

func (x *TransferProto) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProto) GetFromWalletId() string {
	if x != nil {
		return x.FromWalletId
	}
	return ""
}

func (x *TransferProto) GetToWalletId() string {
	if x != nil {
		return x.ToWalletId
	}
	return ""
}

func (x *TransferProto) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferProto) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferProto) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TransferProto) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

var File_api_proto_crypto_v1_crypto_proto protoreflect.FileDescriptor

const file_api_proto_crypto_v1_crypto_proto_rawDesc = "" +
	"\n" +
	" api/proto/crypto/v1/crypto.proto\x12\tcrypto.v1\"\x89\x01\n" +
	"\x13CreateWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x05R\achainId\x12\x1f\n" +
	"\vwallet_type\x18\x04 \x01(\tR\n" +
	"walletType\"F\n" +
	"\x14CreateWalletResponse\x12.\n" +
	"\x06wallet\x18\x01 \x01(\v2\x16.crypto.v1.WalletProtoR\x06wallet\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"C\n" +
	"\x11GetWalletResponse\x12.\n" +
	"\x06wallet\x18\x01 \x01(\v2\x16.crypto.v1.WalletProtoR\x06wallet\"\xd4\x01\n" +
	"\x15ProcessDepositRequest\x12\x1d\n" +
	"\n" +
	"deposit_id\x18\x01 \x01(\tR\tdepositId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\x05R\achainId\x12,\n" +
	"\x12amount_minor_units\x18\x06 \x01(\x03R\x10amountMinorUnits\"K\n" +
	"\x16ProcessDepositResponse\x121\n" +
	"\adeposit\x18\x01 \x01(\v2\x17.crypto.v1.DepositProtoR\adeposit\"\xe3\x01\n" +
	"\x18RequestWithdrawalRequest\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\x05R\achainId\x12,\n" +
	"\x12amount_minor_units\x18\x06 \x01(\x03R\x10amountMinorUnits\"W\n" +
	"\x19RequestWithdrawalResponse\x12:\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2\x1a.crypto.v1.WithdrawalProtoR\n" +
	"withdrawal\"?\n" +
	"\x18ProcessWithdrawalRequest\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\"W\n" +
	"\x19ProcessWithdrawalResponse\x12:\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2\x1a.crypto.v1.WithdrawalProtoR\n" +
	"withdrawal\"\xfc\x01\n" +
	"\x17InternalTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12$\n" +
	"\x0efrom_wallet_id\x18\x02 \x01(\tR\ffromWalletId\x12 \n" +
	"\fto_wallet_id\x18\x03 \x01(\tR\n" +
	"toWalletId\x12&\n" +
	"\x0ffrom_account_id\x18\x04 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x05 \x01(\tR\vtoAccountId\x12,\n" +
	"\x12amount_minor_units\x18\x06 \x01(\x03R\x10amountMinorUnits\"P\n" +
	"\x18InternalTransferResponse\x124\n" +
	"\btransfer\x18\x01 \x01(\v2\x18.crypto.v1.TransferProtoR\btransfer\"\xb3\x01\n" +
	"\vWalletProto\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x05R\achainId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1f\n" +
	"\vwallet_type\x18\x05 \x01(\tR\n" +
	"walletType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x89\x02\n" +
	"\fDepositProto\x12\x1d\n" +
	"\n" +
	"deposit_id\x18\x01 \x01(\tR\tdepositId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\x05R\achainId\x12,\n" +
	"\x12amount_minor_units\x18\x06 \x01(\x03R\x10amountMinorUnits\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12$\n" +
	"\rconfirmations\x18\b \x01(\x05R\rconfirmations\"\xb3\x02\n" +
	"\x0fWithdrawalProto\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\x05R\achainId\x12,\n" +
	"\x12amount_minor_units\x18\x06 \x01(\x03R\x10amountMinorUnits\x12&\n" +
	"\x0ffee_minor_units\x18\a \x01(\x03R\rfeeMinorUnits\x12\x17\n" +
	"\atx_hash\x18\b \x01(\tR\x06txHash\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\x8d\x02\n" +
	"\rTransferProto\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12$\n" +
	"\x0efrom_wallet_id\x18\x02 \x01(\tR\ffromWalletId\x12 \n" +
	"\fto_wallet_id\x18\x03 \x01(\tR\n" +
	"toWalletId\x12&\n" +
	"\x0ffrom_account_id\x18\x04 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x05 \x01(\tR\vtoAccountId\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\x05R\achainId\x12,\n" +
	"\x12amount_minor_units\x18\a \x01(\x03R\x10amountMinorUnits2\x9c\x04\n" +
	"\rCryptoService\x12O\n" +
	"\fCreateWallet\x12\x1e.crypto.v1.CreateWalletRequest\x1a\x1f.crypto.v1.CreateWalletResponse\x12F\n" +
	"\tGetWallet\x12\x1b.crypto.v1.GetWalletRequest\x1a\x1c.crypto.v1.GetWalletResponse\x12U\n" +
	"\x0eProcessDeposit\x12 .crypto.v1.ProcessDepositRequest\x1a!.crypto.v1.ProcessDepositResponse\x12^\n" +
	"\x11RequestWithdrawal\x12#.crypto.v1.RequestWithdrawalRequest\x1a$.crypto.v1.RequestWithdrawalResponse\x12^\n" +
	"\x11ProcessWithdrawal\x12#.crypto.v1.ProcessWithdrawalRequest\x1a$.crypto.v1.ProcessWithdrawalResponse\x12[\n" +
	"\x10InternalTransfer\x12\".crypto.v1.InternalTransferRequest\x1a#.crypto.v1.InternalTransferResponseB7Z5github.com/blazil/crypto/api/proto/crypto/v1;cryptov1b\x06proto3"

var (
	file_api_proto_crypto_v1_crypto_proto_rawDescOnce sync.Once
	file_api_proto_crypto_v1_crypto_proto_rawDescData []byte
)

func file_api_proto_crypto_v1_crypto_proto_rawDescGZIP() []byte {
	file_api_proto_crypto_v1_crypto_proto_rawDescOnce.Do(func() {
		file_api_proto_crypto_v1_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_crypto_v1_crypto_proto_rawDesc), len(file_api_proto_crypto_v1_crypto_proto_rawDesc)))
	})
	return file_api_proto_crypto_v1_crypto_proto_rawDescData
}

var file_api_proto_crypto_v1_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_crypto_v1_crypto_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),       // 0: crypto.v1.CreateWalletRequest
	(*CreateWalletResponse)(nil),      // 1: crypto.v1.CreateWalletResponse
	(*GetWalletRequest)(nil),          // 2: crypto.v1.GetWalletRequest
	(*GetWalletResponse)(nil),         // 3: crypto.v1.GetWalletResponse
	(*ProcessDepositRequest)(nil),     // 4: crypto.v1.ProcessDepositRequest
	(*ProcessDepositResponse)(nil),    // 5: crypto.v1.ProcessDepositResponse
	(*RequestWithdrawalRequest)(nil),  // 6: crypto.v1.RequestWithdrawalRequest
	(*RequestWithdrawalResponse)(nil), // 7: crypto.v1.RequestWithdrawalResponse
	(*ProcessWithdrawalRequest)(nil),  // 8: crypto.v1.ProcessWithdrawalRequest
	(*ProcessWithdrawalResponse)(nil), // 9: crypto.v1.ProcessWithdrawalResponse
	(*InternalTransferRequest)(nil),   // 10: crypto.v1.InternalTransferRequest
	(*InternalTransferResponse)(nil),  // 11: crypto.v1.InternalTransferResponse
	(*WalletProto)(nil),               // 12: crypto.v1.WalletProto
	(*DepositProto)(nil),              // 13: crypto.v1.DepositProto
	(*WithdrawalProto)(nil),           // 14: crypto.v1.WithdrawalProto
	(*TransferProto)(nil),             // 15: crypto.v1.TransferProto
}
var file_api_proto_crypto_v1_crypto_proto_depIdxs = []int32{
	12, // 0: crypto.v1.CreateWalletResponse.wallet:type_name -> crypto.v1.WalletProto
	12, // 1: crypto.v1.GetWalletResponse.wallet:type_name -> crypto.v1.WalletProto
	13, // 2: crypto.v1.ProcessDepositResponse.deposit:type_name -> crypto.v1.DepositProto
	14, // 3: crypto.v1.RequestWithdrawalResponse.withdrawal:type_name -> crypto.v1.WithdrawalProto
	14, // 4: crypto.v1.ProcessWithdrawalResponse.withdrawal:type_name -> crypto.v1.WithdrawalProto
	15, // 5: crypto.v1.InternalTransferResponse.transfer:type_name -> crypto.v1.TransferProto
	0,  // 6: crypto.v1.CryptoService.CreateWallet:input_type -> crypto.v1.CreateWalletRequest
	2,  // 7: crypto.v1.CryptoService.GetWallet:input_type -> crypto.v1.GetWalletRequest
	4,  // 8: crypto.v1.CryptoService.ProcessDeposit:input_type -> crypto.v1.ProcessDepositRequest
	6,  // 9: crypto.v1.CryptoService.RequestWithdrawal:input_type -> crypto.v1.RequestWithdrawalRequest
	8,  // 10: crypto.v1.CryptoService.ProcessWithdrawal:input_type -> crypto.v1.ProcessWithdrawalRequest
	10, // 11: crypto.v1.CryptoService.InternalTransfer:input_type -> crypto.v1.InternalTransferRequest
	1,  // 12: crypto.v1.CryptoService.CreateWallet:output_type -> crypto.v1.CreateWalletResponse
	3,  // 13: crypto.v1.CryptoService.GetWallet:output_type -> crypto.v1.GetWalletResponse
	5,  // 14: crypto.v1.CryptoService.ProcessDeposit:output_type -> crypto.v1.ProcessDepositResponse
	7,  // 15: crypto.v1.CryptoService.RequestWithdrawal:output_type -> crypto.v1.RequestWithdrawalResponse
	9,  // 16: crypto.v1.CryptoService.ProcessWithdrawal:output_type -> crypto.v1.ProcessWithdrawalResponse
	11, // 17: crypto.v1.CryptoService.InternalTransfer:output_type -> crypto.v1.InternalTransferResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_crypto_v1_crypto_proto_init() }
func file_api_proto_crypto_v1_crypto_proto_init() {
	if File_api_proto_crypto_v1_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_crypto_v1_crypto_proto_rawDesc), len(file_api_proto_crypto_v1_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_crypto_v1_crypto_proto_goTypes,
		DependencyIndexes: file_api_proto_crypto_v1_crypto_proto_depIdxs,
		MessageInfos:      file_api_proto_crypto_v1_crypto_proto_msgTypes,
	}.Build()
	File_api_proto_crypto_v1_crypto_proto = out.File
	file_api_proto_crypto_v1_crypto_proto_goTypes = nil
	file_api_proto_crypto_v1_crypto_proto_depIdxs = nil
}
