// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/crypto/v1/crypto.proto

package cryptov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoService_CreateWallet_FullMethodName      = "/crypto.v1.CryptoService/CreateWallet"
	CryptoService_GetWallet_FullMethodName         = "/crypto.v1.CryptoService/GetWallet"
	CryptoService_ProcessDeposit_FullMethodName    = "/crypto.v1.CryptoService/ProcessDeposit"
	CryptoService_RequestWithdrawal_FullMethodName = "/crypto.v1.CryptoService/RequestWithdrawal"
	CryptoService_ProcessWithdrawal_FullMethodName = "/crypto.v1.CryptoService/ProcessWithdrawal"
	CryptoService_InternalTransfer_FullMethodName  = "/crypto.v1.CryptoService/InternalTransfer"
)

// CryptoServiceClient is the client API for CryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CryptoService manages wallets, deposits, withdrawals, and internal transfers.
type CryptoServiceClient interface {
	// CreateWallet provisions a new crypto wallet for an owner on a given chain.
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	// GetWallet retrieves wallet details by ID.
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	// ProcessDeposit finalises a detected inbound deposit.
	ProcessDeposit(ctx context.Context, in *ProcessDepositRequest, opts ...grpc.CallOption) (*ProcessDepositResponse, error)
	// RequestWithdrawal creates a pending outbound withdrawal.
	RequestWithdrawal(ctx context.Context, in *RequestWithdrawalRequest, opts ...grpc.CallOption) (*RequestWithdrawalResponse, error)
	// ProcessWithdrawal broadcasts a pending withdrawal to the chain.
	ProcessWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*ProcessWithdrawalResponse, error)
	// InternalTransfer moves funds between two wallets on the same chain.
	InternalTransfer(ctx context.Context, in *InternalTransferRequest, opts ...grpc.CallOption) (*InternalTransferResponse, error)
}

type cryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoServiceClient(cc grpc.ClientConnInterface) CryptoServiceClient {
	return &cryptoServiceClient{cc}
}

func (c *cryptoServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, CryptoService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, CryptoService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) ProcessDeposit(ctx context.Context, in *ProcessDepositRequest, opts ...grpc.CallOption) (*ProcessDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDepositResponse)
	err := c.cc.Invoke(ctx, CryptoService_ProcessDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) RequestWithdrawal(ctx context.Context, in *RequestWithdrawalRequest, opts ...grpc.CallOption) (*RequestWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWithdrawalResponse)
	err := c.cc.Invoke(ctx, CryptoService_RequestWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) ProcessWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*ProcessWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWithdrawalResponse)
	err := c.cc.Invoke(ctx, CryptoService_ProcessWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) InternalTransfer(ctx context.Context, in *InternalTransferRequest, opts ...grpc.CallOption) (*InternalTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalTransferResponse)
	err := c.cc.Invoke(ctx, CryptoService_InternalTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServiceServer is the server API for CryptoService service.
// All implementations must embed UnimplementedCryptoServiceServer
// for forward compatibility.
//
// CryptoService manages wallets, deposits, withdrawals, and internal transfers.
type CryptoServiceServer interface {
	// CreateWallet provisions a new crypto wallet for an owner on a given chain.
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	// GetWallet retrieves wallet details by ID.
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	// ProcessDeposit finalises a detected inbound deposit.
	ProcessDeposit(context.Context, *ProcessDepositRequest) (*ProcessDepositResponse, error)
	// RequestWithdrawal creates a pending outbound withdrawal.
	RequestWithdrawal(context.Context, *RequestWithdrawalRequest) (*RequestWithdrawalResponse, error)
	// ProcessWithdrawal broadcasts a pending withdrawal to the chain.
	ProcessWithdrawal(context.Context, *ProcessWithdrawalRequest) (*ProcessWithdrawalResponse, error)
	// InternalTransfer moves funds between two wallets on the same chain.
	InternalTransfer(context.Context, *InternalTransferRequest) (*InternalTransferResponse, error)
	mustEmbedUnimplementedCryptoServiceServer()
}

// UnimplementedCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoServiceServer struct{}

func (UnimplementedCryptoServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedCryptoServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedCryptoServiceServer) ProcessDeposit(context.Context, *ProcessDepositRequest) (*ProcessDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessDeposit not implemented")
}
func (UnimplementedCryptoServiceServer) RequestWithdrawal(context.Context, *RequestWithdrawalRequest) (*RequestWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWithdrawal not implemented")
}
func (UnimplementedCryptoServiceServer) ProcessWithdrawal(context.Context, *ProcessWithdrawalRequest) (*ProcessWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWithdrawal not implemented")
}
func (UnimplementedCryptoServiceServer) InternalTransfer(context.Context, *InternalTransferRequest) (*InternalTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalTransfer not implemented")
}
func (UnimplementedCryptoServiceServer) mustEmbedUnimplementedCryptoServiceServer() {}
func (UnimplementedCryptoServiceServer) testEmbeddedByValue()                       {}

// UnsafeCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServiceServer will
// result in compilation errors.
type UnsafeCryptoServiceServer interface {
	mustEmbedUnimplementedCryptoServiceServer()
}

func RegisterCryptoServiceServer(s grpc.ServiceRegistrar, srv CryptoServiceServer) {
	// If the following call panics, it indicates UnimplementedCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoService_ServiceDesc, srv)
}

func _CryptoService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_ProcessDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).ProcessDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_ProcessDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).ProcessDeposit(ctx, req.(*ProcessDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_RequestWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).RequestWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_RequestWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).RequestWithdrawal(ctx, req.(*RequestWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_ProcessWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).ProcessWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_ProcessWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).ProcessWithdrawal(ctx, req.(*ProcessWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_InternalTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).InternalTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_InternalTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).InternalTransfer(ctx, req.(*InternalTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoService_ServiceDesc is the grpc.ServiceDesc for CryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.v1.CryptoService",
	HandlerType: (*CryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _CryptoService_CreateWallet_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _CryptoService_GetWallet_Handler,
		},
		{
			MethodName: "ProcessDeposit",
			Handler:    _CryptoService_ProcessDeposit_Handler,
		},
		{
			MethodName: "RequestWithdrawal",
			Handler:    _CryptoService_RequestWithdrawal_Handler,
		},
		{
			MethodName: "ProcessWithdrawal",
			Handler:    _CryptoService_ProcessWithdrawal_Handler,
		},
		{
			MethodName: "InternalTransfer",
			Handler:    _CryptoService_InternalTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/crypto/v1/crypto.proto",
}
