global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'blazil-dev'
    environment: 'development'

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blazil-engine'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'

  - job_name: 'blazil-payments'
    static_configs:
      - targets: ['localhost:9091']
    metrics_path: '/metrics'

  - job_name: 'blazil-banking'
    static_configs:
      - targets: ['localhost:9092']
    metrics_path: '/metrics'

  - job_name: 'blazil-trading'
    static_configs:
      - targets: ['localhost:9093']
    metrics_path: '/metrics'

  - job_name: 'blazil-crypto'
    static_configs:
      - targets: ['localhost:9094']
    metrics_path: '/metrics'
