// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/payments/v1/payments.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessPaymentRequest is the input to ProcessPayment.
type ProcessPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idempotency_key is a caller-provided deduplication key (required).
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// debit_account_id is the source account (UUID string).
	DebitAccountId string `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	// credit_account_id is the destination account (UUID string).
	CreditAccountId string `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	// amount_minor_units is the payment amount in the smallest currency unit.
	AmountMinorUnits int64 `protobuf:"varint,4,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	// currency_code is the ISO 4217 currency code, e.g. "USD", "EUR", "BTC".
	CurrencyCode string `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// ledger_id identifies the TigerBeetle ledger. USD=1, EUR=2, GBP=3, etc.
	LedgerId uint32 `protobuf:"varint,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	// metadata is optional caller-provided key-value data.
	// The "reference" key is required for authorization.
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ProcessPaymentRequest) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *ProcessPaymentRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ProcessPaymentRequest) GetLedgerId() uint32 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ProcessPaymentResponse is the result of ProcessPayment.
type ProcessPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payment_id is the unique ID assigned by the payments service.
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// status is the final payment status: "settled", "cleared", or "failed".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// rails is the selected payment rail: "internal", "ach", "sepa", "swift", "crypto".
	Rails string `protobuf:"bytes,3,opt,name=rails,proto3" json:"rails,omitempty"`
	// failure_reason contains a human-readable message when status is "failed".
	FailureReason string `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// risk_score is the aggregate risk score from authorization (0–100).
	RiskScore     int32 `protobuf:"varint,5,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetRails() string {
	if x != nil {
		return x.Rails
	}
	return ""
}

func (x *ProcessPaymentResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *ProcessPaymentResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

// GetPaymentRequest is the input to GetPayment.
type GetPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payment_id is the unique payment identifier.
	PaymentId     string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payments_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// GetPaymentResponse contains the payment details.
type GetPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payment_id is the unique payment identifier.
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// status is the current payment status.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// rails is the payment rail.
	Rails string `protobuf:"bytes,3,opt,name=rails,proto3" json:"rails,omitempty"`
	// amount_minor_units is the payment amount in minor units.
	AmountMinorUnits int64 `protobuf:"varint,4,opt,name=amount_minor_units,json=amountMinorUnits,proto3" json:"amount_minor_units,omitempty"`
	// currency_code is the ISO 4217 currency code.
	CurrencyCode  string `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payments_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payments_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentResponse) GetRails() string {
	if x != nil {
		return x.Rails
	}
	return ""
}

func (x *GetPaymentResponse) GetAmountMinorUnits() int64 {
	if x != nil {
		return x.AmountMinorUnits
	}
	return 0
}

func (x *GetPaymentResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

var File_api_proto_payments_v1_payments_proto protoreflect.FileDescriptor

const file_api_proto_payments_v1_payments_proto_rawDesc = "" +
	"\n" +
	"$api/proto/payments/v1/payments.proto\x12\vpayments.v1\"\x91\x03\n" +
	"\x15ProcessPaymentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\tR\x0fcreditAccountId\x12,\n" +
	"\x12amount_minor_units\x18\x04 \x01(\x03R\x10amountMinorUnits\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\rR\bledgerId\x12L\n" +
	"\bmetadata\x18\a \x03(\v20.payments.v1.ProcessPaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x16ProcessPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05rails\x18\x03 \x01(\tR\x05rails\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x05 \x01(\x05R\triskScore\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xb4\x01\n" +
	"\x12GetPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05rails\x18\x03 \x01(\tR\x05rails\x12,\n" +
	"\x12amount_minor_units\x18\x04 \x01(\x03R\x10amountMinorUnits\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode2\xa0\x02\n" +
	"\x0fPaymentsService\x12Y\n" +
	"\x0eProcessPayment\x12\".payments.v1.ProcessPaymentRequest\x1a#.payments.v1.ProcessPaymentResponse\x12c\n" +
	"\x14ProcessPaymentStream\x12\".payments.v1.ProcessPaymentRequest\x1a#.payments.v1.ProcessPaymentResponse(\x010\x01\x12M\n" +
	"\n" +
	"GetPayment\x12\x1e.payments.v1.GetPaymentRequest\x1a\x1f.payments.v1.GetPaymentResponseBFZDgithub.com/blazil/services/payments/api/proto/payments/v1;paymentsv1b\x06proto3"

var (
	file_api_proto_payments_v1_payments_proto_rawDescOnce sync.Once
	file_api_proto_payments_v1_payments_proto_rawDescData []byte
)

func file_api_proto_payments_v1_payments_proto_rawDescGZIP() []byte {
	file_api_proto_payments_v1_payments_proto_rawDescOnce.Do(func() {
		file_api_proto_payments_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payments_v1_payments_proto_rawDesc), len(file_api_proto_payments_v1_payments_proto_rawDesc)))
	})
	return file_api_proto_payments_v1_payments_proto_rawDescData
}

var file_api_proto_payments_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_payments_v1_payments_proto_goTypes = []any{
	(*ProcessPaymentRequest)(nil),  // 0: payments.v1.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 1: payments.v1.ProcessPaymentResponse
	(*GetPaymentRequest)(nil),      // 2: payments.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),     // 3: payments.v1.GetPaymentResponse
	nil,                            // 4: payments.v1.ProcessPaymentRequest.MetadataEntry
}
var file_api_proto_payments_v1_payments_proto_depIdxs = []int32{
	4, // 0: payments.v1.ProcessPaymentRequest.metadata:type_name -> payments.v1.ProcessPaymentRequest.MetadataEntry
	0, // 1: payments.v1.PaymentsService.ProcessPayment:input_type -> payments.v1.ProcessPaymentRequest
	0, // 2: payments.v1.PaymentsService.ProcessPaymentStream:input_type -> payments.v1.ProcessPaymentRequest
	2, // 3: payments.v1.PaymentsService.GetPayment:input_type -> payments.v1.GetPaymentRequest
	1, // 4: payments.v1.PaymentsService.ProcessPayment:output_type -> payments.v1.ProcessPaymentResponse
	1, // 5: payments.v1.PaymentsService.ProcessPaymentStream:output_type -> payments.v1.ProcessPaymentResponse
	3, // 6: payments.v1.PaymentsService.GetPayment:output_type -> payments.v1.GetPaymentResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_payments_v1_payments_proto_init() }
func file_api_proto_payments_v1_payments_proto_init() {
	if File_api_proto_payments_v1_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payments_v1_payments_proto_rawDesc), len(file_api_proto_payments_v1_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payments_v1_payments_proto_goTypes,
		DependencyIndexes: file_api_proto_payments_v1_payments_proto_depIdxs,
		MessageInfos:      file_api_proto_payments_v1_payments_proto_msgTypes,
	}.Build()
	File_api_proto_payments_v1_payments_proto = out.File
	file_api_proto_payments_v1_payments_proto_goTypes = nil
	file_api_proto_payments_v1_payments_proto_depIdxs = nil
}
