apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blazil

resources:
  - namespace.yaml
  - configmap.yaml
  - tigerbeetle/statefulset.yaml
  - tigerbeetle/service.yaml
  - engine/statefulset.yaml
  - engine/service.yaml
  - engine/pdb.yaml
  - payments/deployment.yaml
  - payments/service.yaml
  - banking/deployment.yaml
  - banking/service.yaml
  - trading/deployment.yaml
  - trading/service.yaml
  - crypto/deployment.yaml
  - crypto/service.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: blazil
  app.kubernetes.io/managed-by: kustomize
