// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/trading/v1/trading.proto

package tradingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	OrderId      string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	InstrumentId string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	OwnerId      string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// side: "buy" or "sell"
	Side                 string `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	LimitPriceMinorUnits int64  `protobuf:"varint,5,opt,name=limit_price_minor_units,json=limitPriceMinorUnits,proto3" json:"limit_price_minor_units,omitempty"`
	QuantityUnits        int64  `protobuf:"varint,6,opt,name=quantity_units,json=quantityUnits,proto3" json:"quantity_units,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *PlaceOrderRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PlaceOrderRequest) GetLimitPriceMinorUnits() int64 {
	if x != nil {
		return x.LimitPriceMinorUnits
	}
	return 0
}

func (x *PlaceOrderRequest) GetQuantityUnits() int64 {
	if x != nil {
		return x.QuantityUnits
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderProto            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades        []*TradeProto          `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrder() *OrderProto {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PlaceOrderResponse) GetTrades() []*TradeProto {
	if x != nil {
		return x.Trades
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderProto            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetOrder() *OrderProto {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderProto            `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *OrderProto {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InstrumentId  string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{6}
}

func (x *GetPositionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetPositionRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

type GetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionProto         `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{7}
}

func (x *GetPositionResponse) GetPosition() *PositionProto {
	if x != nil {
		return x.Position
	}
	return nil
}

type ListPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsRequest) Reset() {
	*x = ListPositionsRequest{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsRequest) ProtoMessage() {}

func (x *ListPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsRequest.ProtoReflect.Descriptor instead.
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{8}
}

func (x *ListPositionsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionProto       `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{9}
}

func (x *ListPositionsResponse) GetPositions() []*PositionProto {
	if x != nil {
		return x.Positions
	}
	return nil
}

type OrderProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrderId              string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	InstrumentId         string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	OwnerId              string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Side                 string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	LimitPriceMinorUnits int64                  `protobuf:"varint,5,opt,name=limit_price_minor_units,json=limitPriceMinorUnits,proto3" json:"limit_price_minor_units,omitempty"`
	QuantityUnits        int64                  `protobuf:"varint,6,opt,name=quantity_units,json=quantityUnits,proto3" json:"quantity_units,omitempty"`
	FilledUnits          int64                  `protobuf:"varint,7,opt,name=filled_units,json=filledUnits,proto3" json:"filled_units,omitempty"`
	Status               string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	PlacedAtUnixNano     int64                  `protobuf:"varint,9,opt,name=placed_at_unix_nano,json=placedAtUnixNano,proto3" json:"placed_at_unix_nano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrderProto) Reset() {
	*x = OrderProto{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProto) ProtoMessage() {}

func (x *OrderProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProto.ProtoReflect.Descriptor instead.
func (*OrderProto) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{10}
}

func (x *OrderProto) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderProto) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *OrderProto) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *OrderProto) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderProto) GetLimitPriceMinorUnits() int64 {
	if x != nil {
		return x.LimitPriceMinorUnits
	}
	return 0
}

func (x *OrderProto) GetQuantityUnits() int64 {
	if x != nil {
		return x.QuantityUnits
	}
	return 0
}

func (x *OrderProto) GetFilledUnits() int64 {
	if x != nil {
		return x.FilledUnits
	}
	return 0
}

func (x *OrderProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderProto) GetPlacedAtUnixNano() int64 {
	if x != nil {
		return x.PlacedAtUnixNano
	}
	return 0
}

type TradeProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TradeId            string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	InstrumentId       string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	MakerOrderId       string                 `protobuf:"bytes,3,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId       string                 `protobuf:"bytes,4,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	PriceMinorUnits    int64                  `protobuf:"varint,5,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	QuantityUnits      int64                  `protobuf:"varint,6,opt,name=quantity_units,json=quantityUnits,proto3" json:"quantity_units,omitempty"`
	ExecutedAtUnixNano int64                  `protobuf:"varint,7,opt,name=executed_at_unix_nano,json=executedAtUnixNano,proto3" json:"executed_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TradeProto) Reset() {
	*x = TradeProto{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeProto) ProtoMessage() {}

func (x *TradeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeProto.ProtoReflect.Descriptor instead.
func (*TradeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{11}
}

func (x *TradeProto) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *TradeProto) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *TradeProto) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *TradeProto) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *TradeProto) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *TradeProto) GetQuantityUnits() int64 {
	if x != nil {
		return x.QuantityUnits
	}
	return 0
}

func (x *TradeProto) GetExecutedAtUnixNano() int64 {
	if x != nil {
		return x.ExecutedAtUnixNano
	}
	return 0
}

type PositionProto struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PositionId            string                 `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	OwnerId               string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InstrumentId          string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	QuantityUnits         int64                  `protobuf:"varint,4,opt,name=quantity_units,json=quantityUnits,proto3" json:"quantity_units,omitempty"`
	AverageCostMinorUnits int64                  `protobuf:"varint,5,opt,name=average_cost_minor_units,json=averageCostMinorUnits,proto3" json:"average_cost_minor_units,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PositionProto) Reset() {
	*x = PositionProto{}
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionProto) ProtoMessage() {}

func (x *PositionProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_trading_v1_trading_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionProto.ProtoReflect.Descriptor instead.
func (*PositionProto) Descriptor() ([]byte, []int) {
	return file_api_proto_trading_v1_trading_proto_rawDescGZIP(), []int{12}
}

func (x *PositionProto) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PositionProto) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PositionProto) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *PositionProto) GetQuantityUnits() int64 {
	if x != nil {
		return x.QuantityUnits
	}
	return 0
}

func (x *PositionProto) GetAverageCostMinorUnits() int64 {
	if x != nil {
		return x.AverageCostMinorUnits
	}
	return 0
}

var File_api_proto_trading_v1_trading_proto protoreflect.FileDescriptor

const file_api_proto_trading_v1_trading_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/trading/v1/trading.proto\x12\n" +
	"trading.v1\"\xe0\x01\n" +
	"\x11PlaceOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x125\n" +
	"\x17limit_price_minor_units\x18\x05 \x01(\x03R\x14limitPriceMinorUnits\x12%\n" +
	"\x0equantity_units\x18\x06 \x01(\x03R\rquantityUnits\"r\n" +
	"\x12PlaceOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.trading.v1.OrderProtoR\x05order\x12.\n" +
	"\x06trades\x18\x02 \x03(\v2\x16.trading.v1.TradeProtoR\x06trades\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"C\n" +
	"\x13CancelOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.trading.v1.OrderProtoR\x05order\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"@\n" +
	"\x10GetOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.trading.v1.OrderProtoR\x05order\"T\n" +
	"\x12GetPositionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\"L\n" +
	"\x13GetPositionResponse\x125\n" +
	"\bposition\x18\x01 \x01(\v2\x19.trading.v1.PositionProtoR\bposition\"1\n" +
	"\x14ListPositionsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"P\n" +
	"\x15ListPositionsResponse\x127\n" +
	"\tpositions\x18\x01 \x03(\v2\x19.trading.v1.PositionProtoR\tpositions\"\xc3\x02\n" +
	"\n" +
	"OrderProto\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x125\n" +
	"\x17limit_price_minor_units\x18\x05 \x01(\x03R\x14limitPriceMinorUnits\x12%\n" +
	"\x0equantity_units\x18\x06 \x01(\x03R\rquantityUnits\x12!\n" +
	"\ffilled_units\x18\a \x01(\x03R\vfilledUnits\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12-\n" +
	"\x13placed_at_unix_nano\x18\t \x01(\x03R\x10placedAtUnixNano\"\x9e\x02\n" +
	"\n" +
	"TradeProto\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12$\n" +
	"\x0emaker_order_id\x18\x03 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x04 \x01(\tR\ftakerOrderId\x12*\n" +
	"\x11price_minor_units\x18\x05 \x01(\x03R\x0fpriceMinorUnits\x12%\n" +
	"\x0equantity_units\x18\x06 \x01(\x03R\rquantityUnits\x121\n" +
	"\x15executed_at_unix_nano\x18\a \x01(\x03R\x12executedAtUnixNano\"\xd0\x01\n" +
	"\rPositionProto\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12%\n" +
	"\x0equantity_units\x18\x04 \x01(\x03R\rquantityUnits\x127\n" +
	"\x18average_cost_minor_units\x18\x05 \x01(\x03R\x15averageCostMinorUnits2\x9a\x03\n" +
	"\x0eTradingService\x12K\n" +
	"\n" +
	"PlaceOrder\x12\x1d.trading.v1.PlaceOrderRequest\x1a\x1e.trading.v1.PlaceOrderResponse\x12N\n" +
	"\vCancelOrder\x12\x1e.trading.v1.CancelOrderRequest\x1a\x1f.trading.v1.CancelOrderResponse\x12E\n" +
	"\bGetOrder\x12\x1b.trading.v1.GetOrderRequest\x1a\x1c.trading.v1.GetOrderResponse\x12N\n" +
	"\vGetPosition\x12\x1e.trading.v1.GetPositionRequest\x1a\x1f.trading.v1.GetPositionResponse\x12T\n" +
	"\rListPositions\x12 .trading.v1.ListPositionsRequest\x1a!.trading.v1.ListPositionsResponseB:Z8github.com/blazil/trading/api/proto/trading/v1;tradingv1b\x06proto3"

var (
	file_api_proto_trading_v1_trading_proto_rawDescOnce sync.Once
	file_api_proto_trading_v1_trading_proto_rawDescData []byte
)

func file_api_proto_trading_v1_trading_proto_rawDescGZIP() []byte {
	file_api_proto_trading_v1_trading_proto_rawDescOnce.Do(func() {
		file_api_proto_trading_v1_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_trading_v1_trading_proto_rawDesc), len(file_api_proto_trading_v1_trading_proto_rawDesc)))
	})
	return file_api_proto_trading_v1_trading_proto_rawDescData
}

var file_api_proto_trading_v1_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_trading_v1_trading_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),     // 0: trading.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),    // 1: trading.v1.PlaceOrderResponse
	(*CancelOrderRequest)(nil),    // 2: trading.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 3: trading.v1.CancelOrderResponse
	(*GetOrderRequest)(nil),       // 4: trading.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 5: trading.v1.GetOrderResponse
	(*GetPositionRequest)(nil),    // 6: trading.v1.GetPositionRequest
	(*GetPositionResponse)(nil),   // 7: trading.v1.GetPositionResponse
	(*ListPositionsRequest)(nil),  // 8: trading.v1.ListPositionsRequest
	(*ListPositionsResponse)(nil), // 9: trading.v1.ListPositionsResponse
	(*OrderProto)(nil),            // 10: trading.v1.OrderProto
	(*TradeProto)(nil),            // 11: trading.v1.TradeProto
	(*PositionProto)(nil),         // 12: trading.v1.PositionProto
}
var file_api_proto_trading_v1_trading_proto_depIdxs = []int32{
	10, // 0: trading.v1.PlaceOrderResponse.order:type_name -> trading.v1.OrderProto
	11, // 1: trading.v1.PlaceOrderResponse.trades:type_name -> trading.v1.TradeProto
	10, // 2: trading.v1.CancelOrderResponse.order:type_name -> trading.v1.OrderProto
	10, // 3: trading.v1.GetOrderResponse.order:type_name -> trading.v1.OrderProto
	12, // 4: trading.v1.GetPositionResponse.position:type_name -> trading.v1.PositionProto
	12, // 5: trading.v1.ListPositionsResponse.positions:type_name -> trading.v1.PositionProto
	0,  // 6: trading.v1.TradingService.PlaceOrder:input_type -> trading.v1.PlaceOrderRequest
	2,  // 7: trading.v1.TradingService.CancelOrder:input_type -> trading.v1.CancelOrderRequest
	4,  // 8: trading.v1.TradingService.GetOrder:input_type -> trading.v1.GetOrderRequest
	6,  // 9: trading.v1.TradingService.GetPosition:input_type -> trading.v1.GetPositionRequest
	8,  // 10: trading.v1.TradingService.ListPositions:input_type -> trading.v1.ListPositionsRequest
	1,  // 11: trading.v1.TradingService.PlaceOrder:output_type -> trading.v1.PlaceOrderResponse
	3,  // 12: trading.v1.TradingService.CancelOrder:output_type -> trading.v1.CancelOrderResponse
	5,  // 13: trading.v1.TradingService.GetOrder:output_type -> trading.v1.GetOrderResponse
	7,  // 14: trading.v1.TradingService.GetPosition:output_type -> trading.v1.GetPositionResponse
	9,  // 15: trading.v1.TradingService.ListPositions:output_type -> trading.v1.ListPositionsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_trading_v1_trading_proto_init() }
func file_api_proto_trading_v1_trading_proto_init() {
	if File_api_proto_trading_v1_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_trading_v1_trading_proto_rawDesc), len(file_api_proto_trading_v1_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_trading_v1_trading_proto_goTypes,
		DependencyIndexes: file_api_proto_trading_v1_trading_proto_depIdxs,
		MessageInfos:      file_api_proto_trading_v1_trading_proto_msgTypes,
	}.Build()
	File_api_proto_trading_v1_trading_proto = out.File
	file_api_proto_trading_v1_trading_proto_goTypes = nil
	file_api_proto_trading_v1_trading_proto_depIdxs = nil
}
