// Package report generates a Markdown stress-test report from scenario results.
package report

import (
	"fmt"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/blazil/stresstest/scenarios"
)

// Generate renders a full Markdown report from the collected results.
func Generate(target string, results []scenarios.Result, totalDur time.Duration) string {
	var b strings.Builder

	hw := hwInfo()
	now := time.Now().UTC().Format("2006-01-02 15:04:05 UTC")
	allPass := true
	for _, r := range results {
		if !r.Passed {
			allPass = false
		}
	}
	verdict := "✅ PASSED"
	if !allPass {
		verdict = "❌ FAILED"
	}

	b.WriteString("# Blazil Stress Test Report\n\n")
	b.WriteString(fmt.Sprintf("**Date:** %s  \n", now))
	b.WriteString(fmt.Sprintf("**Target:** `%s`  \n", target))
	b.WriteString(fmt.Sprintf("**Platform:** %s  \n", hw))
	b.WriteString(fmt.Sprintf("**Total test duration:** %.0f s  \n", totalDur.Seconds()))
	b.WriteString(fmt.Sprintf("**Overall verdict:** %s\n\n", verdict))

	b.WriteString("## SLO Targets\n\n")
	b.WriteString("| Metric | Target |\n")
	b.WriteString("|--------|--------|\n")
	b.WriteString("| Sustained TPS | ≥ 10,000 |\n")
	b.WriteString("| P99 latency | ≤ 10 ms |\n")
	b.WriteString("| Error rate | < 0.1 % |\n")
	b.WriteString("| Spike recovery | < one sample window |\n\n")

	b.WriteString("## Scenario Summary\n\n")
	b.WriteString("| Scenario | Result | Peak TPS | Sustained TPS | P99 (ms) | Error % | Notes |\n")
	b.WriteString("|----------|--------|----------|---------------|----------|---------|-------|\n")
	for _, r := range results {
		status := "✅"
		if !r.Passed {
			status = "❌"
		}
		notes := r.Notes
		if notes == "" {
			notes = "—"
		}
		b.WriteString(fmt.Sprintf("| %-10s | %s | %8.0f | %13.0f | %8.2f | %7.2f | %s |\n",
			r.Name, status,
			r.PeakTPS, r.SustainTPS,
			r.P99Ms, r.ErrPct,
			notes,
		))
	}
	b.WriteString("\n")

	// Per-scenario detail sections.
	for _, r := range results {
		b.WriteString(fmt.Sprintf("## Scenario: %s\n\n", r.Name))
		if r.Notes != "" {
			b.WriteString(fmt.Sprintf("> %s\n\n", r.Notes))
		}
		if len(r.Samples) > 0 {
			b.WriteString("| Elapsed | TPS | P50 (ms) | P99 (ms) | Error % |\n")
			b.WriteString("|---------|-----|----------|----------|---------|\n")
			for _, s := range r.Samples {
				b.WriteString(fmt.Sprintf("| %7.0f s | %9.0f | %8.2f | %8.2f | %7.2f |\n",
					s.Elapsed.Seconds(), s.TPS, s.P50Ms, s.P99Ms, s.ErrPct,
				))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("## Conclusion\n\n")
	if allPass {
		b.WriteString("All scenarios passed their SLOs. ")
		b.WriteString("Blazil demonstrates production-grade throughput and low latency ")
		b.WriteString("under sustained load, traffic spikes, and concurrency ramp tests.\n\n")
		b.WriteString("Key results:\n\n")
		for _, r := range results {
			if r.Name == "sustain" {
				b.WriteString(fmt.Sprintf("- **Sustained TPS:** %.0f (target ≥ 10,000)\n", r.SustainTPS))
				b.WriteString(fmt.Sprintf("- **P99 latency:** %.2f ms (target ≤ 10 ms)\n", r.P99Ms))
				b.WriteString(fmt.Sprintf("- **Error rate:** %.3f%% (target < 0.1%%)\n", r.ErrPct))
			}
		}
	} else {
		b.WriteString("One or more scenarios failed their SLOs. See per-scenario notes above.\n")
	}
	b.WriteString("\n---\n")
	b.WriteString("*Generated by `tools/stresstest` — Blazil open-source financial infrastructure.*\n")
	return b.String()
}

// hwInfo returns a one-line hardware summary from the OS.
func hwInfo() string {
	os := runtime.GOOS
	arch := runtime.GOARCH
	cpus := runtime.NumCPU()

	var model string
	switch os {
	case "darwin":
		out, err := exec.Command("sysctl", "-n", "machdep.cpu.brand_string").Output()
		if err == nil {
			model = strings.TrimSpace(string(out))
		}
	case "linux":
		out, err := exec.Command("bash", "-c",
			`grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2`).Output()
		if err == nil {
			model = strings.TrimSpace(string(out))
		}
	}
	if model == "" {
		model = "unknown CPU"
	}
	return fmt.Sprintf("%s/%s (%d cores) — %s", os, arch, cpus, model)
}
