apiVersion: v1
kind: Service
metadata:
  name: blazil-inference
  namespace: blazil
  labels:
    app.kubernetes.io/name: blazil-inference
    app.kubernetes.io/component: inference
spec:
  selector:
    app: blazil-inference
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP
